routes/web.php
<?php

use App\Http\Controllers\CartContrller;

Auth::routes();

Route::redirect('/', '/home');

Route::get('/home', 'HomeController@index')->name('home'); //home controller items list (Home)

Route::get('/add-to-cart/{product_id}','CartContrller@add')->name('cart.add')->middleware('auth');   //Authentication user check

Route::get('/cart','CartContrller@index')->name('cart.index'); //load cart table (normal)

Route::get('/cart/load','CartContrller@load_cart_items_ajax')->name('cart.load_cart_items_ajax'); //load cart table (ajax)

Route::get('/cart/destroy{item_id}','CartContrller@destroy')->name('cart.destroy')->middleware('auth');//cart item delete 

Route::get('/cart/update{item_id}','CartContrller@update')->name('cart.update')->middleware('auth'); //old cart items plus-minus 

Route::get('/cart/update','CartContrller@update_ajax')->name('cart.update_ajax')->middleware('auth'); //cart items plus/minus with ajax

Route::get('/cart/update','CartContrller@update_ajax2')->name('cart.update_ajax2')->middleware('auth'); //cart items plus/minus with ajax

Route::get('/cart/checkout','CartContrller@checkout')->name('cart.checkout')->middleware('auth'); //checkout 
//route::resource()  can delete /update/add ,...in same controller 
Route::resource('orders','OrderController')->middleware('auth'); //Order controller  

Route::get('paypal/checkout','PaypalController@getExpressCheckout'); //paypal controller 

Route::get('paypal/checkout-success','PaypalController@getExpressCheckoutsuccess')->name('paypal.success'); //paypal controller sucess

Route::get('paypal/checkout-cancel','PaypalController@CancelPage')->name('paypal.cancel'); //paypal controller cancel 

resources/views/cart/checkout.blade.php
@extends('layouts.app')
<script
    src="https://www.paypal.com/sdk/js?client-id=AfQlmW9XzXNUL1u9C24_CYCslhB8cvSiRX9ko8B8ZWsn6NcR8Mx02EUNmAAm6S930-6z497qEG31iZz3"> // Required. Replace SB_CLIENT_ID with your sandbox client ID.
  </script>
@section('content')
    <div class="container">
        <div class="">
            <h2>Checkout</h2>
            <h3>Shipping Information</h3>
        </div>
        <div>
        <form action="{{route('orders.store')}}" method="post">
                @csrf
                {{-- @include('_errors') --}}

                <div class="form-group">
                    <label for="shipping_full_name">Full Name</label> 
                    <input id="shipping_full_name" name="shipping_full_name" type="text" required="required" class="form-control">
                  </div>
                  <div class="form-group">
                    <label for="shipping_state">State</label> 
                    <input id="shipping_state" name="shipping_state" type="text" required="required" class="form-control">
                  </div>
                  <div class="form-group">
                    <label for="shipping_city">City</label> 
                    <input id="shipping_city" name="shipping_city" type="text" required="required" class="form-control">
                  </div>
                  <div class="form-group">
                    <label for="shipping_zip">ZIP</label> 
                    <input id="shipping_zip" name="shipping_zip" type="text" required="required" class="form-control">
                  </div>
                  <div class="form-group">
                    <label for="shipping_full_address">Full Address</label> 
                    <input id="shipping_full_address" name="shipping_full_address" type="text" required="required" class="form-control">
                  </div>
                  <div class="form-group">
                    <label for="shipping_mobile">Mobile</label> 
                    <input id="shipping_mobile" name="shipping_mobile" type="text" required="required" class="form-control">
                  </div>
                 
                  <h2>Payment Option</h2>
                  <div class="form-check">
                    <label for="shipping_mobile" class="form-check-label">
                      <input type="radio" class="form-check-input" name="payment_method" value="cash_on_delivery" id="cash_on_delivery" checked>
                      Cash on Delivery 
                    </label> 
                  </div>
                  <div class="form-check">
                    <label for="shipping_mobile" class="form-check-label">
                      <input type="radio" class="form-check-input" name="payment_method" value="paypal" id="paypal" >
                      PayPal
                    </label> 
                  </div>

                  <div class="form-group mt-3">
                    <button name="submit" type="submit" class="btn btn-primary">Place Order</button>
                  </div>
              </form>
              <div id="paypal-button-container"></div>
        </div>
    </div>
   
@endsection

@section('script')
<script type = "application/javascript">

$(function () {

  // paypal.Buttons().render('#paypal-button-container');
  paypal.Buttons({
  enableStandardCardFields: true,


  
  createOrder: function(data, actions) {
    
    return actions.order.create({
      intent: 'CAPTURE',
      payer: {
        name: {
          given_name: "PayPal",
          surname: "Customer"
        },
        address: {
          address_line_1: '123 ABC Street',
          address_line_2: 'Apt 2',
          admin_area_2: 'San Jose',
          admin_area_1: 'CA',
          postal_code: '95121',
          country_code: 'US'
        },
        email_address: "customer@domain.com",
        phone: {
          phone_type: "MOBILE",
          phone_number: {
            national_number: "14082508100"
          }
        }
      },
      purchase_units: [
        {
          amount: {
            value: '15.00',
            currency_code: 'USD'
          },
          shipping: {
            address: {
              address_line_1: '2211 N First Street',
              address_line_2: 'Building 17',
              admin_area_2: 'San Jose',
              admin_area_1: 'CA',
              postal_code: '95131',
              country_code: 'US'
            }
          },
        }
      ]
    });
  }
  
}).render("body");


   }); //on load function end

  

</script>
@endsection

resources/views/cart/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <h2    id    = "test"> Your Cart</h2>
    <table class = "table" id = "cart_table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Quontity</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
   @foreach ($cart_items as $item)
                <tr id = "first_tr">
                    <td hidden>{{$item->id}}</td>
                    <td scope = "row">{{ $item->name }}</td>
                    <td class = "price">
                        {{-- {{ $item->price }} --}}
                        {{ Cart::session(auth()->id())->get($item->id)->getPriceSum()}}
                    </td>
                    <td>
                        <form action="{{route('cart.update',$item->id)}}">
                        <input type="number" id="quantityz" class ="quantityz" name="quantity" value="{{$item->quantity}}">
                        <input type="submit" value="save">
                        {{-- <input type   = "" id          = "item_id" class   = "item_id" value      = "{{$item->id}}"> --}}
                        </form>
                     </td>
                    
                    <td><a href = "{{route('cart.destroy',$item->id)}}">Delete</a></td>
                </tr>
   @endforeach
            </tbody>
        </table>

            <h3>
                Total Price :$ {{ Cart::session(auth()->id())->getTotal()}}
            </h3>
        <h2><a class="btn btn-primary" href="{{route('cart.checkout')}}" role="button">Proceed to checkout</a></h2>
             <div hidden>
                <h2>Jquery Table</h2>
               <table class = "table ajax_cart_table" id = "ajax_cart_table">
                   <thead>
                       <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Price</th>
                            <th>Quontity</th>
                            <th>Action</th>
                       </tr>
                   </thead>
                   <tbody>
                       
                   </tbody>
               </table>
                </div>
</div>

  @endsection

  @section('script')
        <script src = "https://code.jquery.com/jquery-3.3.1.js" defer></script>
        <script src = "//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" defer></script>

        <script type = "application/javascript">
                  $(function () {
                     load_cart_table_ajax();
                    });
        
                
                 function load_cart_table_ajax() {
                                        var tableData = '';
                                        $.ajax({
                                            url : "{{route('cart.load_cart_items_ajax')}}",
                                            type: 'get',
                                            data: {
                                            },
                                            dataType: 'json',
                                            success : function(data) {
                                                if (!($.isEmptyObject(data.error))) {
                                                    // data not found ------
                                                    printErrorMsg(data.error);
                                                    tableData += '<tr><th colspan="4" class="alert alert-warning text-center"> -- No Data Found -- </th></tr>';
             
                                         } else {
                                                    // console.log(data)
                                                    //data found --------
                                                    // $.each(data, function (index, qData) {
                                                    $.each(data, function (index, qData) {
                                                    index++;
                                                    tableData += '<tr>';
                                                    tableData += '<td>' + index + '</td>';
                                                    tableData += '<td>' + qData.name + '</td>';
                                                    tableData += '<td>' + qData.price + '</td>';
                                                    tableData += '<td><input type="number" id="quantity" name="quantity" class="" data-rowId  = "' + qData.price + '"  value="' + qData.quantity + '"></td>';
                                                    tableData += '<td><button id="btn" class="btn btn-danger delStrData btn-sm fa  fa-sm"  data-quantity  = "' + qData.quantity + '"  value="' + qData.quantity + '">&nbsp;Select</button> </td>';

                                                    tableData += '</tr>';
                                                }); 
                                                    $('.ajax_cart_table tbody').html(tableData);
                                                }
                                            }
                                           
                                        });
       }

       //Cart items add/minus function (Ajax data send)===================================
       $(document).on('click', '#btn', function(e) {
        alert($(this).data('quantity'));
       });

       $(document).on('click', '#quantity', function(e) {
                    e.preventDefault();
                    var qty    = $(this).val();
                    var row_id = ($(this).closest('tr').find('td:first').text());

                    // var row_id    =($(this).closest('tr').find('td:first').text());
                    // alert(item_id)
                        $.ajax({
                            url : "{{route('cart.update_ajax2')}}",
                            type: 'get',
                            data: {
                                row_id: row_id,
                                qty   : qty
                            },
                            dataType: 'json',
                            success : function(data) {
                                if ($.isEmptyObject(data.error)) {
                                    // alert(data.success);
                                    // load_cart_table_ajax();
                                } else {
                                    printErrorMsg(data.error);
                                }
                            }
                        });
                    });


           //Cart items add/minus function (Normal data send)===================================
                $(document).on('click', '#quantityz', function(e) {
                    e.preventDefault();
                    var qty    = $(this).val();
                    var row_id = ($(this).closest('tr').find('td:first').text());
                    // alert(item_id)
                        $.ajax({
                            url : "{{route('cart.update_ajax2')}}",
                            type: 'get',
                            data: {
                                row_id: row_id,
                                qty   : qty
                            },
                            dataType: 'json',
                            success : function(data) {
                                if ($.isEmptyObject(data.error)) {
                                    // alert(data.success);
                                    // load_cart_table_ajax();
                                } else {
                                    printErrorMsg(data.error);
                                }
                            }
                        });
                    });


     </script>
 @endsection